on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: checking pull request flow
    steps:
    - name: checking prs
      id: check-pr
      uses: marcoslobo/actions-sme-check@v2
    # Use the output from the `hello` step
    - name: Get the output 
      run: echo "result ${{ steps.check-pr.outputs.sucesso }}"      
      
