on: 
  pull_request:
    branches:
      - master
jobs:
  check-pull-requests:
    runs-on: ubuntu-latest
    name: checking pull request flow
    steps:
    - name: checking prs
      id: check-pr
      uses: marcoslobo/Actions.PRCheck@v5.0.21   
      with:
        branch: 2
    env: 
      branch_ref: ${{ github.head_ref }}
      
