on: 
  pull_request:
    types: [edited, opened, synchronize, reopened]
    branches:
      - master
      
jobs:
  check-pull-requests:
    runs-on: ubuntu-latest
    name: checking pull request flow
    steps:   
      - name: checking prs
        id: check-pr
        uses: marcoslobo/Actions.PRCheck@v5.0.29
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
   
    
      
