on: 
  pull_request:
    branches:
      - master
jobs:
  check-pull-requests:
    runs-on: ubuntu-latest
    name: checking pull request flow
    steps:
    - name: checking prs
      id: check-pr
      uses: marcoslobo/Actions.PRCheck@v5.0.23
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
        echo ${{ github.event.pull_request.title }}    
    
      
