on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: checking pull request flow
    steps:
    - name: checking prs
      id: check-pr
      uses: marcoslobo/Actions.PRCheck@v5.0.9    
    env: 
      branch-ref: $github.head_ref 
      
