on: 
  pull_request:
    branches:
      - master
jobs:
  check-pull-requests:
    runs-on: ubuntu-latest
    name: checking pull request flow 1
    steps:   
      - name: checking prs
        id: check-pr
        uses: marcoslobo/Actions.PRCheck@v5.0.28
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
   
    
      
